name:                crud-builder
version:             0.1.0.0
github:              "ishmum123/crud-builder"
license:             BSD3
author:              "Ishmum Jawad Khan"
maintainer:          "ishmumkhan@gmail.com"
copyright:           "2018 Ishmum Jawad Khan"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ishmum123/crud-builder#readme>

dependencies:
  - base >= 4.7 && < 5
  - text >= 1.2.3.0
  - directory >= 1.3.1.5
  - unordered-containers >= 0.2.9.0
  - filepath >= 1.4.2
  - aeson >= 1.3.1.1
  - bytestring >= 0.10.8.2

library:
  source-dirs: src

executables:
  crud-builder-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - crud-builder

tests:
  crud-builder-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - crud-builder
    - hspec >= 2.0.0
    - QuickCheck
